### ISSUE TITLE
Cannot open Chat popup if performance is too low

### ISSUE THREAD

**Issue by MrModder** [SwarmMind/SwarmMind-Client#13]

**Comment by hesiod** [comment]
Is this still relevant? Pinging @MrModder @Nina510

**Comment by MrModder** [comment]
I dont know if this is still relevant.
I havent done anything to address the issue, as it only occured during a major rework of the rendering loop which tanked performance below 10 fps!
As long as we dont expect any machines to dip performance below 30 fps we should not experience the issue.
Even if the issue still exists I recommend just ignoring it, as the game isnt much fun at such low framerates anyway.
If someone does however want to investigate, I recommend just artificially slowing down the rendering loop by waiting in the rendering loop.
